{{- if .Values.standalone }}
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: {{ include "aif-ui.fullname" . }}
  labels:
    {{- include "aif-ui.labels" . | nindent 4 }}
spec:
  url: http://{{ include "aif-ui.serviceName" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}
{{- end }}

