apiVersion: v1
kind: Service
metadata:
  name: {{ include "sglang.fullname" . }}
  labels:
    {{- include "sglang.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sglang.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
