apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama-cpp.fullname" . }}
  labels:
    {{- include "llama-cpp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llama-cpp.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
